### ISSUE TITLE
Inclusion of the languages "pt" and "pt_BR"

### ISSUE THREAD

**Issue by Lunovox** [minetest-mods/mtg_i18n#10]
Please add the translations below: 
 * https://hosted.weblate.org/projects/minetest/mtg_i18n/pt/
 * https://hosted.weblate.org/projects/minetest/mtg_i18n/pt_BR/

If you can not download the files, I can send them by email, or otherwise.

Thank you! =)

**Comment by lnjX** [comment]
Thank you for reminding me! :)
Everything is merged and the source strings are even updated to Minetest v0.4.17.1.
