### ISSUE TITLE
Small correction in the languages "pt" and "pt_BR"

### ISSUE THREAD

**Issue by Lunovox** [minetest-mods/mtg_i18n#11]
I am grateful for your understanding with me. I did not realize the misspellings in this translation before [recommending these subtitles](https://github.com/minetest/minetest/issues/7944#event-2010685340). I'll be even more grateful if you replace the previous translation "pt" and "pt_BR".

 * https://hosted.weblate.org/projects/minetest/mtg_i18n/pt/
 * https://hosted.weblate.org/projects/minetest/mtg_i18n/pt_BR/

Thank you!

**Comment by lnjX** [comment]
What should I replace?

**Comment by Lunovox** [comment]
> What should I replace?

I applied some corrections in the translations of languages "pt" and "pt_BR" that you can download in the links below. :

 * https://hosted.weblate.org/projects/minetest/mtg_i18n/pt/#download
 * https://hosted.weblate.org/projects/minetest/mtg_i18n/pt_BR/#download

Can you replace the translations 'pt.po' and 'pt_BR.po' in your repository by the files in the links?

**Comment by lnjX** [comment]
Weblate repositories are managed in git, so you generally don't need to replace files.

I merged the updated translations now.

**Comment by Lunovox** [comment]
Ok! Thanks!

# =]
