### ISSUE TITLE
Error with merge Russian translation from Weblate

### ISSUE THREAD

**Issue by kostya13** [minetest-mods/mtg_i18n#15]
I've updated Russian translation on weblate.

But changes don't merged to this repository.

Translate status has exclamation mark and this error message:
https://hosted.weblate.org/projects/minetest/mtg_i18n/#alerts

> The repository could not be merged.
Weblate was unable to merge changes to the top repository when updating this repository.
```
Auto-merging locale/it.po
CONFLICT (content): Merge conflict in locale/it.po
Automatic merge failed; fix conflicts and then commit the result.
 (1)
```

And I don't see my changes in repository.

**Comment by lnjX** [comment]
Thanks, it's fixed.
