### ISSUE TITLE
Lock down Weblate project and inform translators about new translation system

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mtg_i18n#16]
Since Minetest 5.0.0 added native mod translations, it is time to discontinue this project.

I first suggest to lock the Weblate project on <https://hosted.weblate.org/projects/minetest/mtg_i18n> to avoid wasting precious translator time on an outdated project. Meaning that it will be read-only.

Second, please update the README of this project to inform about the new translation system.

Finally, please put this repository on GitHub in archive / read-only mode, so there's no ambiguity about its legacy status.

See also: https://github.com/minetest/minetest_game/issues/2521

**Comment by Wuzzy2** [comment]
Oh, but don't forget to pull down the translations from Weblate one last time before locking down everything.

**Comment by lnjX** [comment]
Alright :)

**Comment by lnjX** [comment]
Unfortunately I don't know how to disable the weblate repository. Probably I don't have the rights to do that or it's not possible.
