### ISSUE TITLE
Dependancy to delete

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/mtg_i18n#2]
https://github.com/minetest-mods/mtg_i18n/blob/696f66153ac4bf11e6a0ff33f3099d83a06e18cb/depends.txt#L15

Mod no longer in Minetest Game.

**Comment by lnjX** [comment]
Thanks for reporting! :smile_cat:

**Comment by bell07** [comment]
Maybe it is a idea to get the mod more robust against such mtg-changes? I am about 
```
-	minetest.override_item(name, {description = description})
+	if core.registered_items[name] then
+		minetest.override_item(name, {description = description})
+	end
```
And then set all mods in depends.txt to optional. In this way the mtg_i18n is compatible to other subgames that contains not all mtg-mods too.

**Comment by lnjX** [comment]
@bell07 Thank you: https://github.com/minetest-mods/mtg_i18n/commit/e82ddadf217727b648adc1d27a9e71c3e5e839ae
