### ISSUE TITLE
Missing strings to be translated.

### ISSUE THREAD

**Issue by ghost** [minetest-mods/mtg_i18n#7]
Checking the items' strings in the creative mode inventory I've seen that some of them don't have an entry in the template.pot - thus they're kept in English.

These are:
string
tin block slab
tin block stair
inner stairs
outer stairs

**Comment by lnjX** [comment]
These are probably new items in the latest dev. I/You can fix this by updating the list in the init.lua.

**Comment by ghost** [comment]
I'm updating it, I'll open a pull request after having checked that it's all ok.

**Comment by mnh48** [comment]
Is the update done yet btw?
I'm translator for Malay and I still didn't see the new items in both template.pot and online weblate so I can't translate them yet.

**Comment by lnjX** [comment]
If you look at the commit history (and the date, when this issue was closed), the last time the source strings were updated was Aug 29, 2017. Please open a pull request to update the source strings. Sorry that I'm not maintaining my minetest mods anymore, but I quitted minetest.

**Comment by mnh48** [comment]
Oh, right.
That explains why some of the items in 0.5.0-dev are translatable but some are not.

Items that are missing were:
- Black Tulip
- Green Chrysanthemum
- Fern
- Kelp On Sand
- Dirt with Coniferous Litter
- Binoculars
- Mapping Kit
